"""i18n 文案字典（简体 / 繁体 / 英文）+ 快捷症状 + 药品名对照"""

TEXTS = {
    "zh-Hans": {
        "title": "Medical Agent",
        "subtitle": "多步医疗对话工作流 · 顺序编排 · 条件短路 · 会话状态管理",
        "lang_label": "语言",
        "session_id": "会话 ID",
        "new_session": "新会话",
        "input_heading": "输入症状",
        "input_label": "症状（逗号分隔）",
        "input_placeholder": "描述你的症状...",
        "name_label": "姓名",
        "name_placeholder": "例如：Tom",
        "analyze": "开始分析",
        "analyzing": "分析中...",
        "analyzing_hint": "预计 5–15 秒，AI 正在分析症状并查询药品信息",
        "no_history": "输入症状并点击「开始分析」",
        "conversation": "对话记录",
        "turn": "第 {n} 轮",
        "emergency": "紧急情况",
        "matched": "匹配症状",
        "skipped": "已跳过步骤",
        "non_emergency": "非紧急",
        "severity": "严重程度",
        "drugs": "推荐药品",
        "for_symptoms": "针对",
        "brand": "品牌",
        "view_warnings": "FDA 原始警示（英文）",
        "no_fda": "未找到 FDA 数据",
        "appointment": "预约时间",
        "event_log": "事件流 · 审计日志",
        "sidebar_title": "会话状态",
        "symptoms_history": "症状历史",
        "most_recent": "最近症状",
        "workflow_stage": "工作流阶段",
        "no_state": "暂无状态",
        "footer": "Azure Functions · Azure OpenAI · openFDA · Blob Storage",
        "stage_input_received": "接收输入",
        "stage_emergency_check": "紧急检测",
        "stage_symptom_analysis": "症状分析",
        "stage_drug_lookup": "药品查询",
        "stage_appointment": "预约安排",
        "stage_completed": "完成",
        "greeting": "你好，{name}。我是你的医疗助手。",
        "greeting_sub": "请描述你的症状，我会为你分析并给出建议。",
        "emergency_msg": "这些症状可能是医疗紧急情况，请立即拨打当地急救电话。",
        "quick_symptoms": "快捷选择",
        "quick_clear": "清空",
        "progress_heading": "处理进度",
        "empty_title": "👋 欢迎使用 Medical Agent",
        "empty_desc": "这是一个多步医疗工作流演示。试试下面的示例：",
        "empty_try_normal": "试试普通症状",
        "empty_try_emergency": "试试紧急症状",
        "usage_advice": "用药建议",
        "self_care": "居家护理",
        "when_to_seek_help": "何时就医",
        "followup": "建议追问",
        "disclaimer": "医疗免责声明",
        "medical_guidance": "医疗建议",
        "possible_causes": "可能的原因",
        "cause_common": "常见",
        "cause_possible": "可能",
        "cause_less_common": "较少见",
        "cause_disclaimer": "以上为常见可能性参考，不构成诊断。如症状持续或加重，请咨询医生。",
    },
    "zh-Hant": {
        "title": "Medical Agent",
        "subtitle": "多步醫療對話工作流 · 順序編排 · 條件短路 · 會話狀態管理",
        "lang_label": "語言",
        "session_id": "會話 ID",
        "new_session": "新會話",
        "input_heading": "輸入症狀",
        "input_label": "症狀（逗號分隔）",
        "input_placeholder": "描述你的症狀...",
        "name_label": "姓名",
        "name_placeholder": "例如：Tom",
        "analyze": "開始分析",
        "analyzing": "分析中...",
        "analyzing_hint": "預計 5–15 秒，AI 正在分析症狀並查詢藥品資料",
        "no_history": "輸入症狀並點擊「開始分析」",
        "conversation": "對話記錄",
        "turn": "第 {n} 輪",
        "emergency": "緊急情況",
        "matched": "匹配症狀",
        "skipped": "已跳過步驟",
        "non_emergency": "非緊急",
        "severity": "嚴重程度",
        "drugs": "推薦藥品",
        "for_symptoms": "針對",
        "brand": "品牌",
        "view_warnings": "FDA 原始警示（英文）",
        "no_fda": "未找到 FDA 資料",
        "appointment": "預約時間",
        "event_log": "事件流 · 審計日誌",
        "sidebar_title": "會話狀態",
        "symptoms_history": "症狀歷史",
        "most_recent": "最近症狀",
        "workflow_stage": "工作流階段",
        "no_state": "暫無狀態",
        "footer": "Azure Functions · Azure OpenAI · openFDA · Blob Storage",
        "stage_input_received": "接收輸入",
        "stage_emergency_check": "緊急檢測",
        "stage_symptom_analysis": "症狀分析",
        "stage_drug_lookup": "藥品查詢",
        "stage_appointment": "預約安排",
        "stage_completed": "完成",
        "greeting": "你好，{name}。我是你的醫療助手。",
        "greeting_sub": "請描述你的症狀，我會為你分析並給出建議。",
        "emergency_msg": "這些症狀可能是醫療緊急情況，請立即撥打當地急救電話。",
        "quick_symptoms": "快捷選擇",
        "quick_clear": "清空",
        "progress_heading": "處理進度",
        "empty_title": "👋 歡迎使用 Medical Agent",
        "empty_desc": "這是一個多步醫療工作流演示。試試下面的示例：",
        "empty_try_normal": "試試普通症狀",
        "empty_try_emergency": "試試緊急症狀",
        "usage_advice": "用藥建議",
        "self_care": "居家護理",
        "when_to_seek_help": "何時就醫",
        "followup": "建議追問",
        "disclaimer": "醫療免責聲明",
        "medical_guidance": "醫療建議",
        "possible_causes": "可能的原因",
        "cause_common": "常見",
        "cause_possible": "可能",
        "cause_less_common": "較少見",
        "cause_disclaimer": "以上為常見可能性參考，不構成診斷。如症狀持續或加重，請諮詢醫生。",
    },
    "en": {
        "title": "Medical Agent",
        "subtitle": "Multi-step medical workflow · Sequential · Conditional short-circuit · Session state",
        "lang_label": "Language",
        "session_id": "Session ID",
        "new_session": "New Session",
        "input_heading": "Enter Symptoms",
        "input_label": "Symptoms (comma-separated)",
        "input_placeholder": "Describe your symptoms...",
        "name_label": "Name",
        "name_placeholder": "e.g. Tom",
        "analyze": "Analyze",
        "analyzing": "Analyzing...",
        "analyzing_hint": "Estimated 5–15 seconds. AI is analyzing symptoms and querying drug data.",
        "no_history": "Enter symptoms and click Analyze",
        "conversation": "Conversation",
        "turn": "Turn {n}",
        "emergency": "EMERGENCY",
        "matched": "Matched symptoms",
        "skipped": "Skipped steps",
        "non_emergency": "Non-emergency",
        "severity": "Severity",
        "drugs": "Recommended drugs",
        "for_symptoms": "For",
        "brand": "Brand",
        "view_warnings": "FDA Original Warnings (English)",
        "no_fda": "No FDA data found",
        "appointment": "Appointment",
        "event_log": "Event Log · Audit Trail",
        "sidebar_title": "Session State",
        "symptoms_history": "Symptoms history",
        "most_recent": "Most recent symptom",
        "workflow_stage": "Workflow stage",
        "no_state": "No state yet",
        "footer": "Azure Functions · Azure OpenAI · openFDA · Blob Storage",
        "stage_input_received": "Input received",
        "stage_emergency_check": "Emergency check",
        "stage_symptom_analysis": "Symptom analysis",
        "stage_drug_lookup": "Drug lookup",
        "stage_appointment": "Appointment",
        "stage_completed": "Completed",
        "greeting": "Hello, {name}. I am your Medical Agent.",
        "greeting_sub": "Describe your symptoms and I'll analyze them for you.",
        "emergency_msg": "These symptoms may be a medical emergency. Call emergency services immediately.",
        "quick_symptoms": "Quick select",
        "quick_clear": "Clear",
        "progress_heading": "Progress",
        "empty_title": "👋 Welcome to Medical Agent",
        "empty_desc": "This is a multi-step medical workflow demo. Try one of the examples below:",
        "empty_try_normal": "Try normal symptoms",
        "empty_try_emergency": "Try emergency symptoms",
        "usage_advice": "Usage Advice",
        "self_care": "Self Care",
        "when_to_seek_help": "When to Seek Help",
        "followup": "Suggested Follow-up",
        "disclaimer": "Medical Disclaimer",
        "medical_guidance": "Medical Guidance",
        "possible_causes": "Possible Causes",
        "cause_common": "Common",
        "cause_possible": "Possible",
        "cause_less_common": "Less Common",
        "cause_disclaimer": "These are common possibilities for reference only, not a diagnosis. Consult a doctor if symptoms persist or worsen.",
    },
}


QUICK_SYMPTOMS = {
    "zh-Hans": [
        ("🤒", "发烧"),
        ("🤕", "头痛"),
        ("😷", "咳嗽"),
        ("🤧", "流鼻涕"),
        ("🤢", "恶心"),
        ("💊", "胃痛"),
    ],
    "zh-Hant": [
        ("🤒", "發燒"),
        ("🤕", "頭痛"),
        ("😷", "咳嗽"),
        ("🤧", "流鼻涕"),
        ("🤢", "噁心"),
        ("💊", "胃痛"),
    ],
    "en": [
        ("🤒", "fever"),
        ("🤕", "headache"),
        ("😷", "cough"),
        ("🤧", "runny nose"),
        ("🤢", "nausea"),
        ("💊", "stomach pain"),
    ],
}


DRUG_NAME_CN = {
    "acetaminophen": "对乙酰氨基酚",
    "ibuprofen": "布洛芬",
    "dextromethorphan": "右美沙芬",
    "loratadine": "氯雷他定",
    "pseudoephedrine": "伪麻黄碱",
    "bismuth subsalicylate": "次水杨酸铋",
    "omeprazole": "奥美拉唑",
    "loperamide": "洛哌丁胺",
    "aspirin": "阿司匹林",
    "diphenhydramine": "苯海拉明",
    "cetirizine": "西替利嗪",
    "fexofenadine": "非索非那定",
    "naproxen": "萘普生",
    "ranitidine": "雷尼替丁",
    "famotidine": "法莫替丁",
    "calcium carbonate": "碳酸钙",
    "magnesium hydroxide": "氢氧化镁",
    "guaifenesin": "愈创木酚甘油醚",
    "phenylephrine": "去氧肾上腺素",
}

DRUG_NAME_TW = {
    "acetaminophen": "乙醯胺酚",
    "ibuprofen": "布洛芬",
    "dextromethorphan": "右美沙芬",
    "loratadine": "氯雷他定",
    "pseudoephedrine": "偽麻黃鹼",
    "bismuth subsalicylate": "次水楊酸鉍",
    "omeprazole": "奧美拉唑",
    "loperamide": "洛哌丁胺",
    "aspirin": "阿斯匹靈",
    "diphenhydramine": "苯海拉明",
    "cetirizine": "西替利嗪",
    "fexofenadine": "非索非那定",
    "naproxen": "萘普生",
    "ranitidine": "雷尼替丁",
    "famotidine": "法莫替丁",
    "calcium carbonate": "碳酸鈣",
    "magnesium hydroxide": "氫氧化鎂",
    "guaifenesin": "癒創木酚甘油醚",
    "phenylephrine": "去氧腎上腺素",
}


def display_drug_name(drug_name: str, lang: str) -> str:
    if lang == "en":
        return drug_name
    mapping = DRUG_NAME_TW if lang == "zh-Hant" else DRUG_NAME_CN
    cn = mapping.get(drug_name.lower())
    return f"{drug_name}（{cn}）" if cn else drug_name


def make_translator(st_module):
    def t(key: str, **kwargs) -> str:
        lang = st_module.session_state.get("lang", "zh-Hans")
        text = TEXTS[lang].get(key, key)
        return text.format(**kwargs) if kwargs else text
    return t